service: cassius-ticket

image: nyshk97/cassius-ticket

servers:
  web:
    - 198.13.52.210

proxy:
  ssl: false
  healthcheck:
    path: /up
    interval: 3
  response_timeout: 30
  forward_headers: true

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 0
    RAILS_MAX_THREADS: 3

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "cassius_ticket_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: root
